services:
  - type: web
    name: web-dai-hoi-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_USER
        fromDatabase:
          name: web-dai-hoi-db
          property: username
      - key: DB_PASS
        fromDatabase:
          name: web-dai-hoi-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: web-dai-hoi-db
          property: hostname
      - key: DB_NAME
        fromDatabase:
          name: web-dai-hoi-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: web-dai-hoi-db
          property: port
      - key: SESSION_SECRET
        sync: false
        value: yourSecretKey
      - key: ADMIN_PASS
        sync: false
        value: yourAdminPassword

  - type: web
    name: web-dai-hoi-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://web-dai-hoi-backend.onrender.com

databases:
  - name: web-dai-hoi-db
    plan: free